#!/bin/bash

declare -A morse
morse=( ["A"]=".-" ["B"]="-..." ["C"]="-.-." ["D"]="-.." ["E"]="." ["F"]="..-." ["G"]="--." ["H"]="...." ["I"]=".." ["J"]=".---"
        ["K"]="-.-" ["L"]=".-.." ["M"]="--" ["N"]="-." ["O"]="---" ["P"]=".--." ["Q"]="--.-" ["R"]=".-." ["S"]="..." ["T"]="-"
        ["U"]=".." ["V"]="...-" ["W"]=".--" ["X"]="-..-" ["Y"]="-." ["Z"]="--.." ["1"]=".----" ["2"]="..---" ["3"]="...--"
        ["4"]="....-" ["5"]="....." ["6"]="-...." ["7"]="--..." ["8"]="---.." ["9"]="----." ["0"]="-----")

send_signal() {
    if [ "$1" == "." ]; then
        termux-torch on
        sleep 0.1
        termux-torch off
        sleep 0.2
    elif [ "$1" == "-" ]; then
        termux-torch on
        sleep 0.8
        termux-torch off
        sleep 0.2
    fi
}

if [ -z "$1" ]; then
    echo "Podaj tekst do przetłumaczenia na Morse'a."
    exit 1
fi

# Zmiana spacji na tabulatory
for char in $(echo "$@" | tr '[:lower:]' '[:upper:]' | sed 's/ /	/g'); do
    if [[ "$char" =~ [A-Z0-9] ]]; then
        morse_code=${morse[$char]}
        for symbol in $(echo "$morse_code" | fold -w1); do
            send_signal "$symbol"
        done
        sleep 1
    elif [ "$char" == "	" ]; then
        sleep 1.5
    fi
done
